# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 19:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import webgallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentName', models.CharField(max_length=200)),
                ('commentContent', models.CharField(max_length=200)),
                ('commentDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='drawingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawingImage', models.ImageField(blank=True, null=True, upload_to=webgallery.models.get_image_path)),
                ('mimeType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='imageEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageTitle', models.CharField(max_length=200)),
                ('imageUrl', models.URLField()),
                ('imageSource', models.CharField(max_length=200)),
            ],
        ),
    ]
